<?php
$admins = $this->getData();
?>
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="Model/Skin/css/style.css">
		<title></title>
	</head>
	<body>
		<?php require_once "View/html/header.phtml" ?>
		<div><div><h3>admin</h3></div><div style="margin-left:640px;margin-top: 15px;">
		<a  class="btn btn-primary" href="<?php echo $this->getModelUrl()->getUrl('add'); ?>">
			add admin
		</a></div></div>
		<br>
		<table class="table table-bordered">
			<tr>
				<th> ADMIN_ID</th>
				<th> NAME</th>
				<th> EMAIL</th>
				<th> STATUS</th>
				<th> </th>
				<th> </th>
			</tr>
			<?php if (!$admins): ?>
			<td colspan="6" >data not found </td>
			<?php else:?>
			
			<?php foreach ($admins as $admin): ?>
			<tr>
				<td><?php echo $admin->admin_id; ?></td>
				<td><?php echo $admin->name; ?></td>
				<td><?php echo $admin->email; ?></td>
				<td><?php echo $admin->getstatustext(); ?></td>
				<td><a href="<?php echo $this->getModelUrl()->getUrl('edit', 'admin', ['admin_id' => $admin->admin_id]); ?>">edit</a></td>
				<td><a href="<?php echo $this->getModelUrl()->getUrl('delete','admin',['admin_id' => $admin->admin_id]); ?>">delete<a></td>
			</tr>
			<?php endforeach; ?>
			<?php endif;?>
		</table>
		<?php require_once "View/html/footer.phtml" ?>
	</body>
</html>